// Code generated by generate-tests; DO NOT EDIT.

package main

import (
	"unicode/utf8"
	. "unicode/utf8"
	pkg "unicode/utf8"
)


func main_utf8() {
	{
		
		_ = utf8.Valid([]byte("foobar")) // want `avoid allocations with utf8\.ValidString`
	}

	{
		
		_ = utf8.Valid([]byte{'f','o','o','b','a','r'}) 
	}

	{
		
		_ = Valid([]byte("foobar")) // want `avoid allocations with utf8\.ValidString`
	}

	{
		
		_ = Valid([]byte{'f','o','o','b','a','r'}) 
	}

	{
		
		_ = pkg.Valid([]byte("foobar")) // want `avoid allocations with utf8\.ValidString`
	}

	{
		
		_ = pkg.Valid([]byte{'f','o','o','b','a','r'}) 
	}

	{
		
		_ = utf8.ValidString(string([]byte{'f','o','o','b','a','r'})) // want `avoid allocations with utf8\.Valid`
	}

	{
		
		_ = utf8.ValidString("foobar") 
	}

	{
		
		_ = ValidString(string([]byte{'f','o','o','b','a','r'})) // want `avoid allocations with utf8\.Valid`
	}

	{
		
		_ = ValidString("foobar") 
	}

	{
		
		_ = pkg.ValidString(string([]byte{'f','o','o','b','a','r'})) // want `avoid allocations with utf8\.Valid`
	}

	{
		
		_ = pkg.ValidString("foobar") 
	}

}
